///////////////////////////////////////////////////////////////////////////////
//  D3DFilteredDevice.inl : the IDirect3DDevice9 methods CD3DFilteredDevice
//  passes straight through, declared here and defined in the .cpp.
///////////////////////////////////////////////////////////////////////////////

	STDMETHOD_(HRESULT, TestCooperativeLevel)();
	STDMETHOD_(UINT, GetAvailableTextureMem)();
	STDMETHOD_(HRESULT, EvictManagedResources)();
	STDMETHOD_(HRESULT, GetDirect3D)(IDirect3D9** ppD3D9);
	STDMETHOD_(HRESULT, GetDeviceCaps)(D3DCAPS9* pCaps);
	STDMETHOD_(HRESULT, GetDisplayMode)(UINT iSwapChain, D3DDISPLAYMODE* pMode);
	STDMETHOD_(HRESULT, GetCreationParameters)(D3DDEVICE_CREATION_PARAMETERS *pParameters);
	STDMETHOD_(HRESULT, SetCursorProperties)(UINT XHotSpot, UINT YHotSpot, IDirect3DSurface9* pCursorBitmap);
	STDMETHOD_(void, SetCursorPosition)(int X, int Y, DWORD Flags);
	STDMETHOD_(BOOL, ShowCursor)(BOOL bShow);
	STDMETHOD_(HRESULT, CreateAdditionalSwapChain)(D3DPRESENT_PARAMETERS* pPresentationParameters, IDirect3DSwapChain9** pSwapChain);
	STDMETHOD_(HRESULT, GetSwapChain)(UINT iSwapChain, IDirect3DSwapChain9** pSwapChain);
	STDMETHOD_(UINT, GetNumberOfSwapChains)();
	STDMETHOD_(HRESULT, GetBackBuffer)(UINT iSwapChain, UINT iBackBuffer, D3DBACKBUFFER_TYPE Type, IDirect3DSurface9** ppBackBuffer);
	STDMETHOD_(HRESULT, GetRasterStatus)(UINT iSwapChain, D3DRASTER_STATUS* pRasterStatus);
	STDMETHOD_(HRESULT, SetDialogBoxMode)(BOOL bEnableDialogs);
	STDMETHOD_(void, SetGammaRamp)(UINT iSwapChain, DWORD Flags, CONST D3DGAMMARAMP* pRamp);
	STDMETHOD_(void, GetGammaRamp)(UINT iSwapChain, D3DGAMMARAMP* pRamp);
	STDMETHOD_(HRESULT, CreateTexture)(UINT Width, UINT Height, UINT Levels, DWORD Usage, D3DFORMAT Format, D3DPOOL Pool, IDirect3DTexture9** ppTexture, HANDLE* pSharedHandle);
	STDMETHOD_(HRESULT, CreateVolumeTexture)(UINT Width, UINT Height, UINT Depth, UINT Levels, DWORD Usage, D3DFORMAT Format, D3DPOOL Pool, IDirect3DVolumeTexture9** ppVolumeTexture, HANDLE* pSharedHandle);
	STDMETHOD_(HRESULT, CreateCubeTexture)(UINT EdgeLength, UINT Levels, DWORD Usage, D3DFORMAT Format, D3DPOOL Pool, IDirect3DCubeTexture9** ppCubeTexture, HANDLE* pSharedHandle);
	STDMETHOD_(HRESULT, CreateVertexBuffer)(UINT Length, DWORD Usage, DWORD FVF, D3DPOOL Pool, IDirect3DVertexBuffer9** ppVertexBuffer, HANDLE* pSharedHandle);
	STDMETHOD_(HRESULT, CreateIndexBuffer)(UINT Length, DWORD Usage, D3DFORMAT Format, D3DPOOL Pool, IDirect3DIndexBuffer9** ppIndexBuffer, HANDLE* pSharedHandle);
	STDMETHOD_(HRESULT, CreateRenderTarget)(UINT Width, UINT Height, D3DFORMAT Format, D3DMULTISAMPLE_TYPE MultiSample, DWORD MultisampleQuality, BOOL Lockable, IDirect3DSurface9** ppSurface, HANDLE* pSharedHandle);
	STDMETHOD_(HRESULT, CreateDepthStencilSurface)(UINT Width, UINT Height, D3DFORMAT Format, D3DMULTISAMPLE_TYPE MultiSample, DWORD MultisampleQuality, BOOL Discard, IDirect3DSurface9** ppSurface, HANDLE* pSharedHandle);
	STDMETHOD_(HRESULT, UpdateSurface)(IDirect3DSurface9* pSourceSurface, CONST RECT* pSourceRect, IDirect3DSurface9* pDestinationSurface, CONST POINT* pDestPoint);
	STDMETHOD_(HRESULT, UpdateTexture)(IDirect3DBaseTexture9* pSourceTexture, IDirect3DBaseTexture9* pDestinationTexture);
	STDMETHOD_(HRESULT, GetRenderTargetData)(IDirect3DSurface9* pRenderTarget, IDirect3DSurface9* pDestSurface);
	STDMETHOD_(HRESULT, GetFrontBufferData)(UINT iSwapChain, IDirect3DSurface9* pDestSurface);
	STDMETHOD_(HRESULT, StretchRect)(IDirect3DSurface9* pSourceSurface, CONST RECT* pSourceRect, IDirect3DSurface9* pDestSurface, CONST RECT* pDestRect, D3DTEXTUREFILTERTYPE Filter);
	STDMETHOD_(HRESULT, ColorFill)(IDirect3DSurface9* pSurface, CONST RECT* pRect, D3DCOLOR color);
	STDMETHOD_(HRESULT, CreateOffscreenPlainSurface)(UINT Width, UINT Height, D3DFORMAT Format, D3DPOOL Pool, IDirect3DSurface9** ppSurface, HANDLE* pSharedHandle);
	STDMETHOD_(HRESULT, SetRenderTarget)(DWORD RenderTargetIndex, IDirect3DSurface9* pRenderTarget);
	STDMETHOD_(HRESULT, GetRenderTarget)(DWORD RenderTargetIndex, IDirect3DSurface9** ppRenderTarget);
	STDMETHOD_(HRESULT, SetDepthStencilSurface)(IDirect3DSurface9* pNewZStencil);
	STDMETHOD_(HRESULT, GetDepthStencilSurface)(IDirect3DSurface9** ppZStencilSurface);
	STDMETHOD_(HRESULT, BeginScene)();
	STDMETHOD_(HRESULT, EndScene)();
	STDMETHOD_(HRESULT, Clear)(DWORD Count, CONST D3DRECT* pRects, DWORD Flags, D3DCOLOR Color, float Z, DWORD Stencil);
	STDMETHOD_(HRESULT, SetViewport)(CONST D3DVIEWPORT9* pViewport);
	STDMETHOD_(HRESULT, GetViewport)(D3DVIEWPORT9* pViewport);
	STDMETHOD_(HRESULT, SetLight)(DWORD Index, CONST D3DLIGHT9* arg1);
	STDMETHOD_(HRESULT, GetLight)(DWORD Index, D3DLIGHT9* arg1);
	STDMETHOD_(HRESULT, LightEnable)(DWORD Index, BOOL Enable);
	STDMETHOD_(HRESULT, GetLightEnable)(DWORD Index, BOOL* pEnable);
	STDMETHOD_(HRESULT, SetClipPlane)(DWORD Index, CONST float* pPlane);
	STDMETHOD_(HRESULT, GetClipPlane)(DWORD Index, float* pPlane);
	STDMETHOD_(HRESULT, SetClipStatus)(CONST D3DCLIPSTATUS9* pClipStatus);
	STDMETHOD_(HRESULT, GetClipStatus)(D3DCLIPSTATUS9* pClipStatus);
	STDMETHOD_(HRESULT, GetSamplerState)(DWORD Sampler, D3DSAMPLERSTATETYPE Type, DWORD* pValue);
	STDMETHOD_(HRESULT, ValidateDevice)(DWORD* pNumPasses);
	STDMETHOD_(HRESULT, SetPaletteEntries)(UINT PaletteNumber, CONST PALETTEENTRY* pEntries);
	STDMETHOD_(HRESULT, GetPaletteEntries)(UINT PaletteNumber, PALETTEENTRY* pEntries);
	STDMETHOD_(HRESULT, SetCurrentTexturePalette)(UINT PaletteNumber);
	STDMETHOD_(HRESULT, GetCurrentTexturePalette)(UINT *PaletteNumber);
	STDMETHOD_(HRESULT, SetScissorRect)(CONST RECT* pRect);
	STDMETHOD_(HRESULT, GetScissorRect)(RECT* pRect);
	STDMETHOD_(HRESULT, SetSoftwareVertexProcessing)(BOOL bSoftware);
	STDMETHOD_(BOOL, GetSoftwareVertexProcessing)();
	STDMETHOD_(HRESULT, SetNPatchMode)(float nSegments);
	STDMETHOD_(float, GetNPatchMode)();
	STDMETHOD_(HRESULT, ProcessVertices)(UINT SrcStartIndex, UINT DestIndex, UINT VertexCount, IDirect3DVertexBuffer9* pDestBuffer, IDirect3DVertexDeclaration9* pVertexDecl, DWORD Flags);
	STDMETHOD_(HRESULT, CreateVertexDeclaration)(CONST D3DVERTEXELEMENT9* pVertexElements, IDirect3DVertexDeclaration9** ppDecl);
	STDMETHOD_(HRESULT, SetVertexDeclaration)(IDirect3DVertexDeclaration9* pDecl);
	STDMETHOD_(HRESULT, GetVertexDeclaration)(IDirect3DVertexDeclaration9** ppDecl);
	STDMETHOD_(HRESULT, SetFVF)(DWORD FVF);
	STDMETHOD_(HRESULT, GetFVF)(DWORD* pFVF);
	STDMETHOD_(HRESULT, CreateVertexShader)(CONST DWORD* pFunction, IDirect3DVertexShader9** ppShader);
	STDMETHOD_(HRESULT, SetVertexShader)(IDirect3DVertexShader9* pShader);
	STDMETHOD_(HRESULT, GetVertexShader)(IDirect3DVertexShader9** ppShader);
	STDMETHOD_(HRESULT, SetVertexShaderConstantF)(UINT StartRegister, CONST float* pConstantData, UINT Vector4fCount);
	STDMETHOD_(HRESULT, GetVertexShaderConstantF)(UINT StartRegister, float* pConstantData, UINT Vector4fCount);
	STDMETHOD_(HRESULT, SetVertexShaderConstantI)(UINT StartRegister, CONST int* pConstantData, UINT Vector4iCount);
	STDMETHOD_(HRESULT, GetVertexShaderConstantI)(UINT StartRegister, int* pConstantData, UINT Vector4iCount);
	STDMETHOD_(HRESULT, SetVertexShaderConstantB)(UINT StartRegister, CONST BOOL* pConstantData, UINT BoolCount);
	STDMETHOD_(HRESULT, GetVertexShaderConstantB)(UINT StartRegister, BOOL* pConstantData, UINT BoolCount);
	STDMETHOD_(HRESULT, SetStreamSource)(UINT StreamNumber, IDirect3DVertexBuffer9* pStreamData, UINT OffsetInBytes, UINT Stride);
	STDMETHOD_(HRESULT, GetStreamSource)(UINT StreamNumber, IDirect3DVertexBuffer9** ppStreamData, UINT* pOffsetInBytes, UINT* pStride);
	STDMETHOD_(HRESULT, SetStreamSourceFreq)(UINT StreamNumber, UINT Setting);
	STDMETHOD_(HRESULT, GetStreamSourceFreq)(UINT StreamNumber, UINT* pSetting);
	STDMETHOD_(HRESULT, SetIndices)(IDirect3DIndexBuffer9* pIndexData);
	STDMETHOD_(HRESULT, GetIndices)(IDirect3DIndexBuffer9** ppIndexData);
	STDMETHOD_(HRESULT, CreatePixelShader)(CONST DWORD* pFunction, IDirect3DPixelShader9** ppShader);
	STDMETHOD_(HRESULT, SetPixelShader)(IDirect3DPixelShader9* pShader);
	STDMETHOD_(HRESULT, GetPixelShader)(IDirect3DPixelShader9** ppShader);
	STDMETHOD_(HRESULT, SetPixelShaderConstantF)(UINT StartRegister, CONST float* pConstantData, UINT Vector4fCount);
	STDMETHOD_(HRESULT, GetPixelShaderConstantF)(UINT StartRegister, float* pConstantData, UINT Vector4fCount);
	STDMETHOD_(HRESULT, SetPixelShaderConstantI)(UINT StartRegister, CONST int* pConstantData, UINT Vector4iCount);
	STDMETHOD_(HRESULT, GetPixelShaderConstantI)(UINT StartRegister, int* pConstantData, UINT Vector4iCount);
	STDMETHOD_(HRESULT, SetPixelShaderConstantB)(UINT StartRegister, CONST BOOL* pConstantData, UINT BoolCount);
	STDMETHOD_(HRESULT, GetPixelShaderConstantB)(UINT StartRegister, BOOL* pConstantData, UINT BoolCount);
	STDMETHOD_(HRESULT, DrawRectPatch)(UINT Handle, CONST float* pNumSegs, CONST D3DRECTPATCH_INFO* pRectPatchInfo);
	STDMETHOD_(HRESULT, DrawTriPatch)(UINT Handle, CONST float* pNumSegs, CONST D3DTRIPATCH_INFO* pTriPatchInfo);
	STDMETHOD_(HRESULT, DeletePatch)(UINT Handle);
	STDMETHOD_(HRESULT, CreateQuery)(D3DQUERYTYPE Type, IDirect3DQuery9** ppQuery);
