//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by AtumAdminTool.rc
//
#define BTN_UPDATE_TO_DB                100
#define ID_CMG_BLOCK_ACCOUNT            101
#define ID_CMG_BLOCK_CHATTING           102
#define ID_CMG_CHANGE_LOCK_CREATE_CHARACTER_FOR_NEW_ACCOUNT	103
#define ID_CMG_DELETE_BLOCKED_USER      104
#define ID_CMG_DELETE_ITEM              105
#define ID_CMG_INSERT_ITEM              106
#define ID_CMG_ITEM_INFORMATION         107
#define ID_CMG_MODIFY_ITEM              108
#define ID_CMG_SERVER_GET_ACCOUNT_LIST  109
#define ID_CMG_SERVER_RELOAD_INFLUENCE_RATE	110
#define ID_CMG_SET_LIMIT_USER_COUNT     111
#define ID_CMG_UNBLOCK                  112
#define ID_CONMENU_ADD_EVENT_MONSTER    113
#define ID_CONMENU_DELETE_EVENT_MONSTER 114
#define ID_CONMENU_MODIFY_EVENT_MONSTER 115
#define ID_MENU_TRAY_EXIT               116
#define ID_MENU_TRAY_OPEN               117
#define ID_MENUITEM_CANCEL              118
#define ID_MENUITEM_DELETE              119
#define ID_MENUITEM_SUMMON              120
#define IDB_BITMAP_CHECK_IMAGE          121
#define IDC_ADMIN_AUTO_NOTICE_LIST      122
#define IDC_APPLICATION_DATEEND         123
#define IDC_APPLICATION_DATESTART       124
#define IDC_APPLICATION_TIMEEND         125
#define IDC_APPLICATION_TIMESTART       126
#define IDC_BTN_ARENA_CHAR_SEND         127
#define IDC_BTN_ARRANGE_LOCAL_RANKING   128
#define IDC_BTN_AUTO_EDIT               129
#define IDC_BTN_BLOCKED_LIST            130
#define IDC_BTN_CANCEL                  131
#define IDC_BTN_CASHSHOP_MANAGEMENT     132
#define IDC_BTN_DECLARATION_OF_WAR      133
#define IDC_BTN_WPSHOP_MANAGEMENT       133
#define IDC_BTN_DEFAULT_VALUES          134
#define IDC_BTN_DELETE                  135
#define IDC_BTN_DELETE_CHARACTER        136
#define IDC_BTN_DELETE_FROM_CHANGED     137
#define IDC_BTN_DELETE_SERVER_GROUP_INFO	138
#define IDC_BTN_DELETE_SERVICE          139
#define IDC_BTN_DOWNLOAD_WRANKING       140
#define IDC_BTN_EDIT_GUILD              141
#define IDC_BTN_EXP_VIEWER              142
#define IDC_BTN_FOR_TESTSERVER          143
#define IDC_BTN_GAMESERVER_RELOAD       144
#define IDC_BTN_GM_EDIT                 145
#define IDC_BTN_GUILD_MARK_RECOGNITION  146
#define IDC_BTN_GUILD_TOOL              147
#define IDC_BTN_IMMEDIAT_OFF            148
#define IDC_BTN_IMMEDIAT_ON             149
#define IDC_BTN_INFINITY                150
#define IDC_BTN_INFINITY_RESET_IMPUTE   151
#define IDC_BTN_INFLWAR_LIST            152
#define IDC_BTN_INIT_INFL_DATA          153
#define IDC_BTN_INIT_INFLUENCE          154
#define IDC_BTN_INIT_MONTHLY_GUILDFAME  155
#define IDC_BTN_INIT_TEXT               156
#define IDC_BTN_INSERT                  157
#define IDC_BTN_LEADER_ELECTION         158
#define IDC_BTN_LOCALIZATION            159
#define IDC_BTN_OK                      160
#define IDC_BTN_PARTNER_SAVE            161
#define IDC_BTN_PARTNER_SOCK_DEL        162
#define IDC_BTN_PARTNER_SOCK_SET        163
#define IDC_BTN_PERIOD_SETTING          164
#define IDC_BTN_PETITION_SYTEM          165
#define IDC_BTN_REALIGNMENT_CASH_ITEM   166
#define IDC_BTN_REG_OR_UPDATE           167
#define IDC_BTN_RELOAD                  168
#define IDC_BTN_RELOAD_ACCOUNT_BLOCKED_LIST	169
#define IDC_BTN_RELOAD_HAPPYEV          170
#define IDC_BTN_RELOAD_HAPPYHOUREV      171
#define IDC_BTN_RELOAD_INFLWARDATA_LIST 172
#define IDC_BTN_RELOAD_MONTHLY_EVENT    173
#define IDC_BTN_RELOAD_PCBANG_LIST      174
#define IDC_BTN_RELOAD_WRANKING         175
#define IDC_BTN_RESULT                  176
#define IDC_BTN_SAVE_RESULT             177
#define IDC_BTN_SEARCHGUILD             178
#define IDC_BTN_SEARCHGUILD_BYGUID      179
#define IDC_BTN_SELECT_PATH             180
#define IDC_BTN_SERVICE_SETTING         181
#define IDC_BTN_SET_InfluenceRate       182
#define IDC_BTN_STATISTICS_MONEY        183
#define IDC_BTN_TO_EXP                  184
#define IDC_BTN_TO_LEVEL                185
#define IDC_BTN_UPDATE                  186
#define IDC_BTN_UPDATE_DB               187
#define IDC_BTN_UPDATE_PCBANG_HAPPYEV   188
#define IDC_BTN_UPDATE_PERIOD_ANI       189
#define IDC_BTN_UPDATE_PERIOD_NORMAL    190
#define IDC_BTN_UPDATE_PERIOD_VCN       191
#define IDC_BTN_UPDATE_RANKING          192
#define IDC_BTN_UPDATE_SERVER_GROUP_NAME	193
#define IDC_BTN_UPDATE_SERVICE          194
#define IDC_BTN_UPDATE_TO_DB            195
#define IDC_BTN_UPDATE_WRANKING         196
#define IDC_BTN_WRANKING_MANAGEMENT     197
#define IDC_BTN_XOR_ENCODE              198
#define IDC_BUTTON1                     199
#define IDC_BUTTON2                     200
#define IDC_BUTTON3                     201
#define IDC_BUTTON4                     202
#define IDC_BUTTON5                     203
#define IDC_BUTTON6                     204
#define IDC_BUTTON7                     205
#define IDC_BUTTON_AUTO_NOTICE          206
#define IDC_BUTTON_BLOCK_ACCOUNT        207
#define IDC_BUTTON_BLOCK_EDIT           208
#define IDC_BUTTON_BLOCK_USER           209
#define IDC_BUTTON_CHARAC_1_OK          210
#define IDC_BUTTON_CHARAC_2_OK          211
#define IDC_BUTTON_CHARAC_3_OK          212
#define IDC_BUTTON_CONNECT              213
#define IDC_BUTTON_CREATE               214
#define IDC_BUTTON_DELETE               215
#define IDC_BUTTON_DELETED_CHARACTER    216
#define IDC_BUTTON_DETAIL_DELETE        217
#define IDC_BUTTON_DETAIL_INSERT        218
#define IDC_BUTTON_DETAIL_REFRESH       219
#define IDC_BUTTON_DETAIL_SELECT        220
#define IDC_BUTTON_DETAIL_UPDATE        221
#define IDC_BUTTON_DISCONNECT           222
#define IDC_BUTTON_DISELECT_ALL         223
#define IDC_BUTTON_DOWN                 224
#define IDC_BUTTON_EDIT_ACCOUNT         225
#define IDC_BUTTON_EDIT_ARMOR_COLLECTION	226
#define IDC_BUTTON_EDIT_CHARACTER       227
#define IDC_BUTTON_EDIT_PREMIUM         228
#define IDC_BUTTON_END                  229
#define IDC_BUTTON_EVENT_MONSTER        230
#define IDC_BUTTON_FORBID_UPDATE        231
#define IDC_BUTTON_GET_USER_INFO        232
#define IDC_BUTTON_HAPPY_HOUR_EVENT_TOOL	233
#define IDC_BUTTON_INFO                 234
#define IDC_BUTTON_ITEM_EVENT           235
#define IDC_BUTTON_LIST_LOAD            236
#define IDC_BUTTON_LIST_SAVE            237
#define IDC_BUTTON_LOAD_DATA            238
#define IDC_BUTTON_LOG_TOOL             239
#define IDC_BUTTON_LUCKYMACHINE_INIT    240
#define IDC_BUTTON_MARKET_LOG           241
#define IDC_BUTTON_MARKET_RESET         242
#define IDC_BUTTON_MARKET_SAVE_RESULT   243
#define IDC_BUTTON_MARKET_SEARCH        244
#define IDC_BUTTON_MARKET_TRADE_REMOVE_ALL	245
#define IDC_BUTTON_MARKET_TRADE_SELECT_ALL	246
#define IDC_BUTTON_MD5_PWD              247
#define IDC_BUTTON_MD5_SECPWD           248
#define IDC_BUTTON_MONTHLY_ARMOR_EVENT  249
#define IDC_BUTTON_MONTHLY_SEARCH       250
#define IDC_BUTTON_MS_START_UPDATE      251
#define IDC_BUTTON_OK                   252
#define IDC_BUTTON_OUTPOST              253
#define IDC_BUTTON_REFRESH              254
#define IDC_BUTTON_RELOAD               255
#define IDC_BUTTON_RESET                256
#define IDC_BUTTON_SAVE                 257
#define IDC_BUTTON_SAVE_FILE            258
#define IDC_BUTTON_SCREEN_SHOT_VIEWER   259
#define IDC_BUTTON_SEARCH               260
#define IDC_BUTTON_SELECT               261
#define IDC_BUTTON_SELECT_ALL           262
#define IDC_BUTTON_SELECT_ITEM          263
#define IDC_BUTTON_SEND_CHAT            264
#define IDC_BUTTON_SERVER               265
#define IDC_BUTTON_SETTING_SAVE         266
#define IDC_BUTTON_STEP_SELECT          267
#define IDC_BUTTON_STEP_START_UPDATE    268
#define IDC_BUTTON_STOP_SOUND           269
#define IDC_BUTTON_STRATEGYPOINT        270
#define IDC_BUTTON_STRATEGYPOINT_APPLY  271
#define IDC_BUTTON_STRATEGYPOINT_SAVE   272
#define IDC_BUTTON_STRATEGYPOINT_SUMMON_RANGE	273
#define IDC_BUTTON_STRATEGYPOINT_SUMMON_RANGE_INIT	274
#define IDC_BUTTON_TOTAL_DELETE         275
#define IDC_BUTTON_TOTAL_DELETE2        276
#define IDC_BUTTON_TOTAL_INSERT         277
#define IDC_BUTTON_TOTAL_INSERT2        278
#define IDC_BUTTON_TOTAL_UPDATE         279
#define IDC_BUTTON_TOTAL_UPDATE2        280
#define IDC_BUTTON_TOTALSET_REFRESH     281
#define IDC_BUTTON_TOTALSET_SELECT      282
#define IDC_BUTTON_UNBLOCK_ACCOUNT      283
#define IDC_BUTTON_UP                   284
#define IDC_BUTTON_UPDATE               285
#define IDC_BUTTON_UPDATE_STRATEGYPOINT_NOTSUMMONTIME	286
#define IDC_BUTTON_USER_TOOL            287
#define IDC_CHANNELING_CHECK            288
#define IDC_CHECK1                      289
#define IDC_CHECK_SEARCH_AUCTION_ITEM   289
#define IDC_CHECK2                      290
#define IDC_CHECK_ACCOUNT_BLOCKED       291
#define IDC_CHECK_ACCOUNT_NAME          292
#define IDC_CHECK_ACCOUNT_NAME2         293
#define IDC_CHECK_AccountName           294
#define IDC_CHECK_AccountUID            295
#define IDC_CHECK_ADD_ITEM_BY_ADMIN     296
#define IDC_CHECK_ADD_ITEM_BY_COMMAND   297
#define IDC_CHECK_ADMIN_ACCOUNT_NAME    298
#define IDC_CHECK_ALL                   299
#define IDC_CHECK_Bazaar_Buy            300
#define IDC_CHECK_Bazaar_Sell           301
#define IDC_CHECK_BLOCK_DATE            302
#define IDC_CHECK_BLOCKEDTYPE           303
#define IDC_CHECK_BUY_ITEM              304
#define IDC_CHECK_CANCEL_TRADE          305
#define IDC_CHECK_CHARACTER             306
#define IDC_CHECK_CHARACTER2            307
#define IDC_CHECK_CHARACTER_ITEM        308
#define IDC_CHECK_CHARACTERNAME         309
#define IDC_CHECK_CHATTING_BLOCKED      310
#define IDC_CHECK_CHECK_WITH_ACCOUNTEXT_UID	311
#define IDC_CHECK_CHECK_WITH_ACCOUNTUID 312
#define IDC_CHECK_CHECK_WITH_CHARACTERUID	313
#define IDC_CHECK_DATE                  314
#define IDC_CHECK_DEL_ITEM_BY_ADMIN     315
#define IDC_CHECK_SEARCH_AUCTION_ITEM_DATE 315
#define IDC_CHECK_DISENCHANT_BY_ADMIN   316
#define IDC_CHECK_DRAW_FROM_STORE       317
#define IDC_CHECK_DRAW_GUILDSTORE       318
#define IDC_CHECK_ENCHANT_BY_ADMIN      319
#define IDC_CHECK_EXCEPT_INFL_MON       320
#define IDC_CHECK_EXCEPT_NOT_ATTACK_MON 321
#define IDC_CHECK_EXCEPT_OBJ_MON        322
#define IDC_CHECK_FIXED_PERIOD          323
#define IDC_CHECK_GAP_TIME_DAY          324
#define IDC_CHECK_GAP_TIME_HOUR         325
#define IDC_CHECK_GAP_TIME_MINUTE       326
#define IDC_CHECK_GAP_TIME_MONTH        327
#define IDC_CHECK_GAP_TIME_YEAR         328
#define IDC_CHECK_GET_EXCHANGE          329
#define IDC_CHECK_GET_ITEM              330
#define IDC_CHECK_GIFT_RECV             331
#define IDC_CHECK_GIFT_SEND             332
#define IDC_CHECK_GUILD_UID             333
#define IDC_CHECK_GUILDNAME             334
#define IDC_CHECK_INSERT_GUILDSTORE     335
#define IDC_CHECK_INSERT_TO_STORE       336
#define IDC_CHECK_IP_ADDRESS            337
#define IDC_CHECK_ITEM_DISSOLUTION      338
#define IDC_CHECK_ITEM_MIX              339
#define IDC_CHECK_ITEM_NUM              340
#define IDC_CHECK_ITEM_UID              341
#define IDC_CHECK_ITEMNAME              342
#define IDC_CHECK_ITEMNUM               343
#define IDC_CHECK_LAST_GAME_END_DATE    344
#define IDC_CHECK_LOG_BLOCK             345
#define IDC_CHECK_LOG_LOGIN             346
#define IDC_CHECK_LOG_LOGOUT            347
#define IDC_CHECK_LOG_UNBLOCK           348
#define IDC_CHECK_MARKET_CHARACTER_NAME 349
#define IDC_CHECK_MARKET_CHARACTER_UID  350
#define IDC_CHECK_MARKET_INFLUENCE      351
#define IDC_CHECK_MAX_ROW_COUNT         352
#define IDC_CHECK_PLAY_TIME_1           353
#define IDC_CHECK_AUCTIONT_STATUS_1     353
#define IDC_CHECK_PLAY_TIME_2           354
#define IDC_CHECK_SEARCH_AUCTION_ITEM_STATUS 354
#define IDC_CHECK_REARRANGEITEM_DELETE  355
#define IDC_CHECK_REARRANGEITEM_ITEM    356
#define IDC_CHECK_REQUIRED_ITEM_1       357
#define IDC_CHECK_REQUIRED_ITEM_2       358
#define IDC_CHECK_SELL_ITEM             359
#define IDC_CHECK_SET_INFL_LEADER       360
#define IDC_CHECK_SetForAll             361
#define IDC_CHECK_SetForLevel           362
#define IDC_CHECK_SOURCE_CHARACTER_NAME 363
#define IDC_CHECK_SOURCE_CHARACTER_UID  364
#define IDC_CHECK_SOURCE_DB_NUM         365
#define IDC_CHECK_STORE_START_ITEM      366
#define IDC_CHECK_TARGET_CHARACTER_NAME 367
#define IDC_CHECK_TARGET_CHARACTER_UID  368
#define IDC_CHECK_TARGET_DB_NUM         369
#define IDC_CHECK_THROWAWAY_ITEM        370
#define IDC_CHECK_TRADE_RECV            371
#define IDC_CHECK_TRADE_SEND            372
#define IDC_CHECK_TRY_ENCHANT_INFO      373
#define IDC_CHECK_USE_ENCHANT           374
#define IDC_CHECK_USE_ENERGY            375
#define IDC_CHECK_USE_ITEM              376
#define IDC_CHECK_USE_SPI               377
#define IDC_CHECK_USE_WP                378
#define IDC_CHECK_USER_CREATE_CHARACTER 379
#define IDC_CHECK_USER_DEAD             380
#define IDC_CHECK_USER_DELETE_CHARACTER 381
#define IDC_CHECK_USER_DELETE_CHARACTER_BY_ADMIN	382
#define IDC_CHECK_USER_EXP_CHANGE       383
#define IDC_CHECK_USER_GAMEEND          384
#define IDC_CHECK_USER_GAMESTART        385
#define IDC_CHECK_USER_LEVEL_CHANGE     386
#define IDC_CHECK_USER_MEMORY_HACK      387
#define IDC_CHECK_USER_PVE_LOSS         388
#define IDC_CHECK_USER_PVE_WIN          389
#define IDC_CHECK_USER_PVP_LOSE         390
#define IDC_CHECK_USER_PVP_WIN          391
#define IDC_CHECK_USER_QUEST_END        392
#define IDC_CHECK_USER_SPEED_HACK       393
#define IDC_CHECK_USER_STAT_CHANGE      394
#define IDC_CHECK_USER_WARP             395
#define IDC_CHECKInflSub2Leader         396
#define IDC_CHECKNUMBER_EDIT            397
#define IDC_CHECKSubLeader              398
#define IDC_CHOICE_CHANNELING_COMBO     399
#define IDC_CMDLG_COMBO_OPTION          400
#define IDC_CMDLG_DATEPICKER_DATE       401
#define IDC_CMDLG_EDIT_OPTION_NAME      402
#define IDC_CMDLG_EDIT_REMAIN_TIME_INPUT	403
#define IDC_CMDLG_EDIT_REMAIN_TIME_OUTPUT	404
#define IDC_CMDLG_EDIT_SHAPE_LEVEL      405
#define IDC_CMDLG_EDIT_SHAPE_NAME       406
#define IDC_CMDLG_EDIT_SHAPE_NUM        407
#define IDC_CMDLG_TIMEPICKER_TIME       408
#define IDC_COMBO1                      409
#define IDC_COMBO_ACC_OR_CHARAC2        410
#define IDC_COMBO_ACC_OR_CHARAC_USER_TOOL	411
#define IDC_COMBO_ADD_ENCHANT           412
#define IDC_COMBO_BLOCK_TYPE            413
#define IDC_COMBO_CHAT_HISTORY          414
#define IDC_COMBO_COLORCODE             415
#define IDC_COMBO_DETAIL_DAYOFWEEK      416
#define IDC_COMBO_ENCHANT_ITEMNUM_LIST  417
#define IDC_COMBO_GAP_TIME_DAY          418
#define IDC_COMBO_GAP_TIME_HOUR         419
#define IDC_COMBO_GAP_TIME_MINUTE       420
#define IDC_COMBO_GAP_TIME_MONTH        421
#define IDC_COMBO_GAP_TIME_YEAR         422
#define IDC_COMBO_GUILD_MARK_STATE      423
#define IDC_COMBO_INDEX_TYPE            424
#define IDC_COMBO_INFLUENCE_TYPE_LIST   425
#define IDC_COMBO_INFLUENCETYPE         426
#define IDC_COMBO_ITEM                  427
#define IDC_COMBO_ITEM_KIND             428
#define IDC_COMBO_ITEMEVENT_PREFIX      429
#define IDC_COMBO_ITEMEVENT_SUFFIX      430
#define IDC_COMBO_OPTION_LIST           431
#define IDC_COMBO_PARTNER_POSSESS_SOCKET_LIST	432
#define IDC_COMBO_PREFIX                433
#define IDC_COMBO_PREMIUM_ITEM          434
#define IDC_COMBO_RACE                  435
#define IDC_COMBO_RACE_ACC_TYPE         436
#define IDC_COMBO_RACE_ACC_TYPE2        437
#define IDC_COMBO_SELECTED_INFLUENCE_TYPE	438
#define IDC_COMBO_SERVER                439
#define IDC_COMBO_SELECTED_AUCTION_PERIOD 439
#define IDC_COMBO_SERVER_               440
#define IDC_COMBO_SELECTED_AUCTION_STATUS_1 440
#define IDC_COMBO_SERVER_GROUP          441
#define IDC_COMBO_SELECTED_SEARCH_AUCTION_ITEM 441
#define IDC_COMBO_SHAPEITEMNUM          442
#define IDC_COMBO_SELECTED_SEARCH_AUCTION_ITEM_STATUS 442
#define IDC_COMBO_SUB_ENCHANT           443
#define IDC_COMBO_SUFFIX                444
#define IDC_COUNT_EDIT                  445
#define IDC_CUSTOM_MONTHLY_ARMOR_EVENT_LIST	446
#define IDC_CUSTOM_MONTHLY_SHAPE_ITEM_LIST	447
#define IDC_DATEPICKER_ANI_END          448
#define IDC_DATEPICKER_ANI_START        449
#define IDC_DATEPICKER_END              450
#define IDC_DATEPICKER_NORMAL_END       451
#define IDC_DATEPICKER_NORMAL_START     452
#define IDC_DATEPICKER_PCBANG_END       453
#define IDC_DATEPICKER_PCBANG_START     454
#define IDC_DATEPICKER_START            455
#define IDC_DATEPICKER_VCN_END          456
#define IDC_DATEPICKER_VCN_START        457
#define IDC_DATETIME_EFRIDAY            458
#define IDC_DATETIME_EMONDAY            459
#define IDC_DATETIME_END_DATE           460
#define IDC_DATETIME_END_TIME           461
#define IDC_DATETIME_ESATURDAY          462
#define IDC_DATETIME_ESUNDAY            463
#define IDC_DATETIME_ETHURSDAY          464
#define IDC_DATETIME_ETUESDAY           465
#define IDC_DATETIME_EWEDNESDAY         466
#define IDC_DATETIME_FRIENDTIME         467
#define IDC_DATETIME_FRISTARTTIME       468
#define IDC_DATETIME_MONENDTIME         469
#define IDC_DATETIME_MONSTARTTIME       470
#define IDC_DATETIME_SATENDTIME         471
#define IDC_DATETIME_SATSTARTTIME       472
#define IDC_DATETIME_SFRIDAY            473
#define IDC_DATETIME_SMONDAY            474
#define IDC_DATETIME_SSATURDAY          475
#define IDC_DATETIME_SSUNDAY            476
#define IDC_DATETIME_START_DATE         477
#define IDC_DATETIME_START_TIME         478
#define IDC_DATETIME_STHURSDAY          479
#define IDC_DATETIME_STUESDAY           480
#define IDC_DATETIME_SUNENDTIME         481
#define IDC_DATETIME_SUNSTARTTIME       482
#define IDC_DATETIME_SWEDNESDAY         483
#define IDC_DATETIME_THUENDTIME         484
#define IDC_DATETIME_THUSTARTTIME       485
#define IDC_DATETIME_TUEENDTIME         486
#define IDC_DATETIME_TUESTARTTIME       487
#define IDC_DATETIME_WEDENDTIME         488
#define IDC_DATETIME_WEDSTARTTIME       489
#define IDC_DATETIMEPICKER1             490
#define IDC_DATETIMEPICKER2             491
#define IDC_DATETIMEPICKER3             492
#define IDC_DATETIMEPICKER4             493
#define IDC_DATETIMEPICKER5             494
#define IDC_DATETIMEPICKER6             495
#define IDC_DATETIMEPICKER7             496
#define IDC_DATETIMEPICKER8             497
#define IDC_DATETIMEPICKER_AT_TIME      498
#define IDC_DATETIMEPICKER_CREATED_DATE 499
#define IDC_DATETIMEPICKER_CREATED_TIME 500
#define IDC_DATETIMEPICKER_DETAIL_ENDTIME	501
#define IDC_DATETIMEPICKER_DETAIL_STARTDATE	502
#define IDC_DATETIMEPICKER_DETAIL_STARTTIME	503
#define IDC_DATETIMEPICKER_END_DATE     504
#define IDC_DATETIMEPICKER_END_TIME     505
#define IDC_DATETIMEPICKER_ENDDATE      506
#define IDC_DATETIMEPICKER_ENDTIME      507
#define IDC_DATETIMEPICKER_EXPIRE_DATE  508
#define IDC_DATETIMEPICKER_EXPIRE_TIME  509
#define IDC_DATETIMEPICKER_GETDATE      510
#define IDC_DATETIMEPICKER_GETTIME      511
#define IDC_DATETIMEPICKER_LAST_DATE    512
#define IDC_DATETIMEPICKER_LAST_TIME    513
#define IDC_DATETIMEPICKER_NEXTWARDATE  514
#define IDC_DATETIMEPICKER_NEXTWARTIME  515
#define IDC_DATETIMEPICKER_START_DATE   516
#define IDC_DATETIMEPICKER_START_TIME   517
#define IDC_DATETIMEPICKER_START_DATE_SEARCH_AUCTION_ITEM 517
#define IDC_DATETIMEPICKER_STARTDATE    518
#define IDC_DATETIMEPICKER_STARTTIME    519
#define IDC_DATETIMEPICKER_UPDATED_DATE 520
#define IDC_DATETIMEPICKER_UPDATED_TIME 521
#define IDC_DOWN                        522
#define IDC_DTPICKER_END_DATE           523
#define IDC_DTPICKER_END_TIME           524
#define IDC_DTPICKER_START_DATE         525
#define IDC_DTPICKER_START_TIME         526
#define IDC_EDIT1                       527
#define IDC_EDIT2                       528
#define IDC_EDIT3                       529
#define IDC_EDIT5                       530
#define IDC_EDIT6                       531
#define IDC_EDIT7                       532
#define IDC_EDIT_A_ACC_NAME             533
#define IDC_EDIT_A_ATT_NAME             534
#define IDC_EDIT_A_DEF_NAME             535
#define IDC_EDIT_A_DOD_NAME             536
#define IDC_EDIT_ACC_TYPE               537
#define IDC_EDIT_ACCNAME                538
#define IDC_EDIT_ACCOUNT_NAME           539
#define IDC_EDIT_ACCOUNT_NAME2          540
#define IDC_EDIT_ACCOUNTNAME            541
#define IDC_EDIT_ACCOUNTUID             542
#define IDC_EDIT_ADMIN_ACCOUNT_NAME     543
#define IDC_EDIT_ADMIN_NAME             544
#define IDC_EDIT_ARENA_CWP              545
#define IDC_EDIT_ARENA_DISCONNECT       546
#define IDC_EDIT_ARENA_LOSE             547
#define IDC_EDIT_ARENA_WIN              548
#define IDC_EDIT_ARENA_WP               549
#define IDC_EDIT_ARMOR_ENCHANT_RATE     550
#define IDC_EDIT_ARMOR_ENCHANT_RATE2    551
#define IDC_EDIT_ARMOR_ENCHANT_RATE3    552
#define IDC_EDIT_B_ACC_NAME             553
#define IDC_EDIT_B_ATT_NAME             554
#define IDC_EDIT_B_DEF_NAME             555
#define IDC_EDIT_B_DOD_NAME             556
#define IDC_EDIT_BIRTH_YEAR             557
#define IDC_EDIT_BONUS_STAT             558
#define IDC_EDIT_BONUS_STAT_POINT       559
#define IDC_EDIT_CHANNEL_INDEX          560
#define IDC_EDIT_CHARAC_NAME_1          561
#define IDC_EDIT_CHARAC_NAME_2          562
#define IDC_EDIT_CHARAC_NAME_3          563
#define IDC_EDIT_CHARACTER_NAME         564
#define IDC_EDIT_CHARACTER_NAME2        565
#define IDC_EDIT_CHAT_MESSAGE           566
#define IDC_EDIT_CITYMAP                567
#define IDC_EDIT_DELAY_TIME             568
#define IDC_EDIT_DP                     569
#define IDC_EDIT_DP_CUR                 570
#define IDC_EDIT_DROPITEMRATE           571
#define IDC_EDIT_DROPRAREITEMRATE       572
#define IDC_EDIT_DURATION               573
#define IDC_EDIT_ELECTION_STATE         574
#define IDC_EDIT_ENCHNT_COUNT           575
#define IDC_EDIT_ENCOEDED_STRING        576
#define IDC_EDIT_EP                     577
#define IDC_EDIT_EP_CUR                 578
#define IDC_EDIT_ETC_ITEM_ENCHANT_RATE  579
#define IDC_EDIT_ETC_ITEM_ENCHANT_RATE2 580
#define IDC_EDIT_ETC_ITEM_ENCHANT_RATE3 581
#define IDC_EDIT_EVENT_INDEX            582
#define IDC_EDIT_EXP                    583
#define IDC_EDIT_EXP_PER                584
#define IDC_EDIT_EXPRATE                585
#define IDC_EDIT_EXPREPAIRRATE          586
#define IDC_EDIT_FRIANI                 587
#define IDC_EDIT_FRIBCU                 588
#define IDC_EDIT_GUILD_NAME             589
#define IDC_EDIT_GUILD_UID              590
#define IDC_EDIT_GUILDUID               591
#define IDC_EDIT_HP                     592
#define IDC_EDIT_HP_CUR                 593
#define IDC_EDIT_HP_RECOVERY_RATE       594
#define IDC_EDIT_HP_RECOVERY_RATE2      595
#define IDC_EDIT_HP_RECOVERY_RATE3      596
#define IDC_EDIT_I_ACC_NAME             597
#define IDC_EDIT_I_ATT_NAME             598
#define IDC_EDIT_I_DEF_NAME             599
#define IDC_EDIT_I_DOD_NAME             600
#define IDC_EDIT_INFLUENCE              601
#define IDC_EDIT_INPUT_ARMOR            602
#define IDC_EDIT_INSERT_ENCHANT_COUNT   603
#define IDC_EDIT_IntervalTime           604
#define IDC_EDIT_ITEM_COUNT             605
#define IDC_EDIT_ITEM_MAX_LOG_COUNT     606
#define IDC_EDIT_ITEM_NAME              607
#define IDC_EDIT_ITEM_NUM               608
#define IDC_EDIT_ITEM_TOTAL_LOG_COUNT   609
#define IDC_EDIT_ITEM_UID               610
#define IDC_EDIT_KEY_STRING             611
#define IDC_EDIT_LANG_INFO              612
#define IDC_EDIT_LANG_TYPE              613
#define IDC_EDIT_LANGUAGE               614
#define IDC_EDIT_LAST_LOGIN_DATE        615
#define IDC_EDIT_LEVEL                  616
#define IDC_EDIT_LOCALIZATION_PATH      617
#define IDC_EDIT_LoopTime               618
#define IDC_EDIT_M_ACC_NAME             619
#define IDC_EDIT_M_ATT_NAME             620
#define IDC_EDIT_M_DEF_NAME             621
#define IDC_EDIT_M_DOD_NAME             622
#define IDC_EDIT_MAP_INDEX              623
#define IDC_EDIT_MAPINDEX               624
#define IDC_EDIT_MARKET_CHARACTER_NAME  625
#define IDC_EDIT_MARKET_CHARACTER_UID   626
#define IDC_EDIT_MAX_ROW_COUNT          627
#define IDC_EDIT_MAX_SUMMON_COUNT_DAILY 628
#define IDC_EDIT_MAXLEVEL               629
#define IDC_EDIT_MINLEVEL               630
#define IDC_EDIT_MONANI                 631
#define IDC_EDIT_MONBCU                 632
#define IDC_EDIT_MONSTER_COUNT          633
#define IDC_EDIT_MONSTERNUM             634
#define IDC_EDIT_NEXTWARTIMESET         635
#define IDC_EDIT_OUTPOSTMAP             636
#define IDC_EDIT_OUTPUT                 637
#define IDC_EDIT_PART_ATTACK            638
#define IDC_EDIT_PART_DEFENSE           639
#define IDC_EDIT_PART_DODGE             640
#define IDC_EDIT_PART_FUEL              641
#define IDC_EDIT_PART_SHIELD            642
#define IDC_EDIT_PART_SOUL              643
#define IDC_EDIT_PARTNER_ACCOUNT_NAME   644
#define IDC_EDIT_PARTNER_CHARACTER      645
#define IDC_EDIT_PARTNER_EXP_CURRENT    646
#define IDC_EDIT_PARTNER_EXP_MAX        647
#define IDC_EDIT_PARTNER_EXP_PERCENTAGE 648
#define IDC_EDIT_PARTNER_LV_CURRENT     649
#define IDC_EDIT_PARTNER_LV_CURRENT_SPIN	650
#define IDC_EDIT_PARTNER_LV_MAX         651
#define IDC_EDIT_PARTNER_NAME           652
#define IDC_EDIT_PARTNER_SOCKET         653
#define IDC_EDIT_PARTNER_TYPE           654
#define IDC_EDIT_PASSWORD               655
#define IDC_EDIT_PCBangTotalPlayTime    656
#define IDC_EDIT_PERCENT                657
#define IDC_EDIT_POS_X                  658
#define IDC_EDIT_POS_Z                  659
#define IDC_EDIT_POSITION               660
#define IDC_EDIT_PROBABILITY            661
#define IDC_EDIT_PROPENSITY             662
#define IDC_EDIT_PWD                    663
#define IDC_EDIT_PWD_                   664
#define IDC_EDIT_RACING_POINT           665
#define IDC_EDIT_REASON                 666
#define IDC_EDIT_REASON_FOR_ONLY_ADMIN  667
#define IDC_EDIT_REG_DATE               668
#define IDC_EDIT_REMOVE_ENCHANT_COUNT   669
#define IDC_EDIT_REQ_MAX_LEVEL          670
#define IDC_EDIT_REQ_MIN_LEVEL          671
#define IDC_EDIT_SATANI                 672
#define IDC_EDIT_SATBCU                 673
#define IDC_EDIT_SEARCH_GUILDNAME       674
#define IDC_EDIT_SEARCH_GUILDUID        675
#define IDC_EDIT_SECPASSWORD            676
#define IDC_EDIT_SELECT                 677
#define IDC_EDIT_SELECTED_ITEM          678
#define IDC_EDIT_SERVER_GROUP_ID        679
#define IDC_EDIT_SERVER_GROUP_NAME      680
#define IDC_EDIT_SERVICE_NAME           681
#define IDC_EDIT_SERVICEUID             682
#define IDC_EDIT_SEX                    683
#define IDC_EDIT_SHD_RECOVERY_RATE      684
#define IDC_EDIT_SHD_RECOVERY_RATE2     685
#define IDC_EDIT_SHD_RECOVERY_RATE3     686
#define IDC_EDIT_SOURCE_CHARACTER_NAME  687
#define IDC_EDIT_SOURCE_CHARACTER_UID   688
#define IDC_EDIT_SOURCE_DB_NUM          689
#define IDC_EDIT_SOURCE_STRING          690
#define IDC_EDIT_SP                     691
#define IDC_EDIT_SP_CUR                 692
#define IDC_EDIT_SP_RECOVERY_RATE       693
#define IDC_EDIT_SP_RECOVERY_RATE2      694
#define IDC_EDIT_SP_RECOVERY_RATE3      695
#define IDC_EDIT_SPI_DISCOUNT_RATE      696
#define IDC_EDIT_SPI_DISCOUNT_RATE2     697
#define IDC_EDIT_SPI_DISCOUNT_RATE3     698
#define IDC_EDIT_SPIRATE                699
#define IDC_EDIT_STEP                   700
#define IDC_EDIT_STRATEGYPOINT_SUMMON_CHECK	701
#define IDC_EDIT_SUMMON_RANGE           702
#define IDC_EDIT_SUNANI                 703
#define IDC_EDIT_SUNBCU                 704
#define IDC_EDIT_SYMBOL_IMAGE_PATH      705
#define IDC_EDIT_TARGET_CHARACTER_NAME  706
#define IDC_EDIT_TARGET_CHARACTER_UID   707
#define IDC_EDIT_TARGET_DB_NUM          708
#define IDC_EDIT_THUANI                 709
#define IDC_EDIT_THUBCU                 710
#define IDC_EDIT_TOTAL_EXP              711
#define IDC_EDIT_TOTAL_LOG_COUNTS       712
#define IDC_EDIT_TOTAL_LOG_ROW_COUNT    713
#define IDC_EDIT_TUEANI                 714
#define IDC_EDIT_TUEBCU                 715
#define IDC_EDIT_UID                    716
#define IDC_EDIT_UID_                   717
#define IDC_EDIT_USER_COUNT             718
#define IDC_EDIT_USER_INPUT             719
#define IDC_EDIT_VOTE_NUMBER            720
#define IDC_EDIT_WEAPON_ENCHANT_RATE    721
#define IDC_EDIT_WEAPON_ENCHANT_RATE2   722
#define IDC_EDIT_WEAPON_ENCHANT_RATE3   723
#define IDC_EDIT_WEDANI                 724
#define IDC_EDIT_WEDBCU                 725
#define IDC_EDIT_WP_DISCOUNT_RATE       726
#define IDC_EDIT_WP_DISCOUNT_RATE2      727
#define IDC_EDIT_WP_DISCOUNT_RATE3      728
#define IDC_EDIT_WPRATE                 729
#define IDC_ELECTION_DATE               730
#define IDC_ELECTION_TIME               731
#define IDC_FIND_FILE                   732
#define IDC_FIXEDPERIOD_DAY_EDIT        733
#define IDC_FORBID_DATEEND              734
#define IDC_FORBID_DATESTART            735
#define IDC_FORBID_TIMEEND              736
#define IDC_FORBID_TIMESTART            737
#define IDC_FORBID_TIMESTART2           738
#define IDC_GRAPH_TAB                   739
#define IDC_GRID_ANI                    740
#define IDC_GRID_BAD_USER               741
#define IDC_GRID_BCU                    742
#define IDC_GRID_BLOCKACCOUNT_LOG       743
#define IDC_GRID_BLOCKED_LIST           744
#define IDC_GRID_CHANGED_ITEM           745
#define IDC_GRID_CHARACTER              746
#define IDC_GRID_COLLECTION_ADD_LIST    747
#define IDC_GRID_COLLECTION_LIST        748
#define IDC_GRID_COMBATPOWER_LOG        749
#define IDC_GRID_CONNECTION_LOG         750
#define IDC_GRID_CUR_ITEM               751
#define IDC_GRID_CUR_REALIGN_ITEM       752
#define IDC_GRID_DECLARATION_OF_WAR_LIST	753
#define IDC_GRID_DELETED_CHARACTER_LIST 754
#define IDC_GRID_EVENT_DETAIL           755
#define IDC_GRID_EVENT_MONSTER_LIST     756
#define IDC_GRID_EVENT_TOTAL            757
#define IDC_GRID_GIFT_LIST              758
#define IDC_GRID_GUILD                  759
#define IDC_GRID_GUILD_MARK_LIST        760
#define IDC_GRID_GUILDITEMS             761
#define IDC_GRID_GUILDMEMBER            762
#define IDC_GRID_INFLWAR_LIST           763
#define IDC_GRID_ITEM                   764
#define IDC_GRID_ITEM_EVENT_LIST        765
#define IDC_GRID_ITEM_LOG               766
#define IDC_GRID_OUTPOST_INFO_LIST      767
#define IDC_GRID_SERVER_INFO            768
#define IDC_GRID_SERVERINTEGRATION_LOG  769
#define IDC_GRID_SET_FOR_ALL            770
#define IDC_GRID_SET_FOR_LEVEL          771
#define IDC_GRID_STAISTICSMONEY         772
#define IDC_GRID_STRATEGYPOINT_INFO_LIST	773
#define IDC_GRID_STRATEGYPOINT_RANGE_LIST	774
#define IDC_GRID_STRATEGYPOINT_TODAY_LIST	775
#define IDC_GRID_TRADE_MARKET           776
#define IDC_GRID_USER_LOG               777
#define IDC_GRID_VOTE_RESULT_LIST       778
#define IDC_IPADDRESS                   779
#define IDC_ITEM_EVENT_ADMIN_TOOL_BUTTON_OK	780
#define IDC_ITEM_EVENT_SUB_TYPE_REQUIRED_ITEM	781
#define IDC_ITEM_EVENT_TYPE_AtTime_CHECK	782
#define IDC_ITEM_EVENT_TYPE_COUPON_ONEDAY	783
#define IDC_ITEM_EVENT_TYPE_COUPON_ONLYONE	784
#define IDC_ITEM_EVENT_TYPE_FIRST_PURCHASE	785
#define IDC_ITEM_EVENT_TYPE_INFL_ALL_CHECK	786
#define IDC_ITEM_EVENT_TYPE_INFL_ANI_CHECK	787
#define IDC_ITEM_EVENT_TYPE_INFL_NORMAL_CHECK	788
#define IDC_ITEM_EVENT_TYPE_INFL_VCN_CHECK	789
#define IDC_ITEM_EVENT_TYPE_INFLCHANGE  790
#define IDC_ITEM_EVENT_TYPE_LEVELUP     791
#define IDC_ITEM_EVENT_TYPE_LOGINEVENT  792
#define IDC_ITEM_EVENT_TYPE_OneDay_CHECK	793
#define IDC_ITEM_EVENT_TYPE_OnlyOne_CHECK	794
#define IDC_ITEM_EVENT_TYPE_UNITKIND_AGEAR_CHECK	795
#define IDC_ITEM_EVENT_TYPE_UNITKIND_BGEAR_CHECK	796
#define IDC_ITEM_EVENT_TYPE_UNITKIND_IGEAR_CHECK	797
#define IDC_ITEM_EVENT_TYPE_UNITKIND_MGEAR_CHECK	798
#define IDC_ITEMNUM_EDIT                799
#define IDC_LEVEL_EDIT                  800
#define IDC_LEVELMAX                    801
#define IDC_LEVELMIN                    802
#define IDC_MEMBERSHIP_CHECK            803
#define IDC_MS_DATESTART                804
#define IDC_MS_TIMESTART                805
#define IDC_NEWMEMBER_CHECK             806
#define IDC_NOTICE_ADD                  807
#define IDC_NOTICE_DELETE               808
#define IDC_NOTICE_DOWN                 809
#define IDC_NOTICE_UP                   810
#define IDC_PCBANG_CHECK                811
#define IDC_PLACEHOLDER                 812
#define IDC_PROGRESS1                   813
#define IDC_PROPENSITY                  814
#define IDC_RADIO1                      815
#define IDC_RADIO_ACCOUNT               816
#define IDC_RADIO_ACCOUNT_UID           817
#define IDC_RADIO_CHARACTER             818
#define IDC_RADIO_CHARACTER_UID         819
#define IDC_RADIO_CHINESE               820
#define IDC_RADIO_ENGLISH               821
#define IDC_RADIO_JAPANESE              822
#define IDC_RADIO_KOREAN                823
#define IDC_RADIO_NO                    824
#define IDC_RADIO_VIETNAMESE            825
#define IDC_RADIO_YES                   826
#define IDC_RELOAD_ITEM_EVENT_BUTTON    827
#define IDC_SET_ITEM_EVENT_BUTTON_OK    828
#define IDC_SLIDER_PARTNER              829
#define IDC_STATI_CCMDLG_8              830
#define IDC_STATIC_ACC_TYPE             831
#define IDC_STATIC_ACC_TYPE2            832
#define IDC_STATIC_ACC_TYPE4            833
#define IDC_STATIC_ACC_TYPE5            834
#define IDC_STATIC_ACCNAME              835
#define IDC_STATIC_ACCOUNT              836
#define IDC_STATIC_ADD_INFO             837
#define IDC_STATIC_ALL                  838
#define IDC_STATIC_ANI                  839
#define IDC_STATIC_ARMOR_INFO           840
#define IDC_STATIC_BLOCK_PERIOD         841
#define IDC_STATIC_BLOCK_REASON         842
#define IDC_STATIC_BLOCK_TYPE           843
#define IDC_STATIC_BLOCK_TYPE2          844
#define IDC_STATIC_CHARAC_1             845
#define IDC_STATIC_CHARAC_2             846
#define IDC_STATIC_CHARAC_3             847
#define IDC_STATIC_CMDLG_1              848
#define IDC_STATIC_CMDLG_2              849
#define IDC_STATIC_CMDLG_3              850
#define IDC_STATIC_CMDLG_4              851
#define IDC_STATIC_CMDLG_5              852
#define IDC_STATIC_CMDLG_7              853
#define IDC_STATIC_CMDLG_9              854
#define IDC_STATIC_CONNECTION           855
#define IDC_STATIC_EVENT_DATE           856
#define IDC_STATIC_EVENT_INFO           857
#define IDC_STATIC_EVENT_NUM            858
#define IDC_STATIC_EVENT_NUM2           859
#define IDC_STATIC_EVENT_NUM3           860
#define IDC_STATIC_EVENT_NUM4           861
#define IDC_STATIC_EVENT_NUM5           862
#define IDC_STATIC_EXP                  863
#define IDC_STATIC_INFLUENCETYPE        864
#define IDC_STATIC_ITEM_COUNT           865
#define IDC_STATIC_ITEM_INFO            866
#define IDC_STATIC_ITEM_INFO2           867
#define IDC_STATIC_KIND                 868
#define IDC_STATIC_LANGUAGE             869
#define IDC_STATIC_NORMAL               870
#define IDC_STATIC_OPTION               871
#define IDC_STATIC_POSITION             872
#define IDC_STATIC_QUESTION             873
#define IDC_STATIC_RACING_POINT         874
#define IDC_STATIC_SEARCH               875
#define IDC_STATIC_SEX                  876
#define IDC_STATIC_SEARCH2              876
#define IDC_STATIC_SEX2                 877
#define IDC_STATIC_TOOLS                878
#define IDC_STATIC_TOOLS2               879
#define IDC_STATIC_TOTAL_USER_COUNT     880
#define IDC_STATIC_USER                 881
#define IDC_STATIC_USER_INFO            882
#define IDC_STATIC_VCN                  883
#define IDC_STEP_DATESTART              884
#define IDC_STEP_TIMESTART              885
#define IDC_SUB_EVENT_CHECK_STATIC      886
#define IDC_SUMMON_CHECK_FRIDAY         887
#define IDC_SUMMON_CHECK_MONDAY         888
#define IDC_SUMMON_CHECK_SATURDAY       889
#define IDC_SUMMON_CHECK_SUNDAY         890
#define IDC_SUMMON_CHECK_THURSDAY       891
#define IDC_SUMMON_CHECK_TUESDAY        892
#define IDC_SUMMON_CHECK_WEDNESDAY      893
#define IDC_TAB_LOG_ADMIN_TOOL          894
#define IDC_TAB_MARKET_LOG              895
#define IDC_TIMEPICKER_ANI_END          896
#define IDC_TIMEPICKER_ANI_START        897
#define IDC_TIMEPICKER_END              898
#define IDC_TIMEPICKER_NORMAL_END       899
#define IDC_TIMEPICKER_NORMAL_START     900
#define IDC_TIMEPICKER_PCBANG_END       901
#define IDC_TIMEPICKER_PCBANG_START     902
#define IDC_TIMEPICKER_START            903
#define IDC_TIMEPICKER_VCN_END          904
#define IDC_TIMEPICKER_VCN_START        905
#define IDC_TTEM_EVENT_SUB_TYPE_PLAY_TIME	906
#define IDC_UP                          907
#define IDC_VOTE_DATEEND                908
#define IDC_VOTE_DATESTART              909
#define IDC_VOTE_TIMEEND                910
#define IDC_VOTE_TIMESTART              911
#define IDD_ATUMADMINTOOL_DIALOG        912
#define IDD_DIALOG_ADMIN_AUTO_NOTICE    913
#define IDD_DIALOG_ARENA_CHAR_SEND      914
#define IDD_DIALOG_ATUM_ADMIN_TOOL      915
#define IDD_DIALOG_ATUM_ADMIN_TOOL_BUTTON	916
#define IDD_DIALOG_BAD_USER_ADMIN_TOOL  917
#define IDD_DIALOG_CHARACTER_INFO       918
#define IDD_DIALOG_COMBATPOWER_DETAIL   919
#define IDD_DIALOG_CONNECT_SERVER       920
#define IDD_DIALOG_EDIT_ACCOUNT         921
#define IDD_DIALOG_HAPPY_HOUR_EVENT_ADMIN	922
#define IDD_DIALOG_INSERT_ITEM          923
#define IDD_DIALOG_ITEM_EVENT_ADMIN     924
#define IDD_DIALOG_LOG_ADMIN_TOOL       925
#define IDD_DIALOG_MARKET_LOG_MANAGEMENT	926
#define IDD_DIALOG_MODIFY_ITEM          927
#define IDD_DIALOG_PARTNER              928
#define IDD_DIALOG_PWD                  929
#define IDD_DIALOG_RENEWAL_STRATEGYPOINT	930
#define IDD_DIALOG_SELECT_ITEM          931
#define IDD_DIALOG_SERVER_ADMIN_TOOL    932
#define IDD_DIALOG_STATISTICS_MONEY     933
#define IDD_DIALOG_STRATEGYPOINT_ADMIN_TOOL	934
#define IDD_DIALOG_USER_ADMIN_TOOL      935
#define IDD_DLG_                        936
#define IDD_DLG_ARMOR_COLLECTION        937
#define IDD_DLG_ARMOR_COLLECTION_ADD    938
#define IDD_DLG_ARMOR_COLLECTION_MODIFY 939
#define IDD_DLG_BLOCK_ACCOUNT           940
#define IDD_DLG_BLOCK_ACCOUNT_LIST      941
#define IDD_DLG_CASHSHOP_MANAGEMENT     942
#define IDD_DLG_DECLARATION_OF_WAR      943
#define IDD_DLG_DELETED_CHARACTER       944
#define IDD_DLG_EDIT_GUILD              945
#define IDD_DLG_EVENT_MONSTER           946
#define IDD_DLG_EVENT_MONSTER_MANAGEMENT	947
#define IDD_DLG_EXP_VIEWER              948
#define IDD_DLG_GUILD_ADMIN             949
#define IDD_DLG_GUILD_MARK_RECOGNITION  950
#define IDD_DLG_INFLWAR_LIST            951
#define IDD_DLG_LEADER_ELECTION         952
#define IDD_DLG_LOCALIZATION            953
#define IDD_DLG_MONTHLY_ARMOR_EVENT     954
#define IDD_DLG_MSGBOX                  955
#define IDD_DLG_OUTPOST                 956
#define IDD_DLG_PETITION_MANAGEMENT     957
#define IDD_DLG_PREMIUM                 958
#define IDD_DLG_REALIGNMENT_CASH_ITEM   959
#define IDD_DLG_SET_HAPPYEV             960
#define IDD_DLG_SET_INFLUENCE_RATE      961
#define IDD_DLG_SET_ITEMEV              962
#define IDD_DLG_SET_LIMIT_USER_COUNT    963
#define IDD_DLG_SET_PCBANG_HAPPYEV      964
#define IDD_DLG_WRK_MANAGEMENT          965
#define IDD_DLG_WRK_SERVICE_SETTING     966
#define IDD_DLG_WRK_UPDATE_RANKING      967
#define IDD_DLG_XOR_TEST                968
#define IDD_LOG_TAB_BLOCKACCOUNT        969
#define IDD_LOG_TAB_COMBATPOWER         970
#define IDD_LOG_TAB_CONNECTION          971
#define IDD_LOG_TAB_GUILDITEM           972
#define IDD_LOG_TAB_ITEM                973
#define IDD_LOG_TAB_SERVERINTEGRATION   974
#define IDD_LOG_TAB_USER                975
#define IDD_MARKET_TAB_TRADE            976
#define IDD_SCUSERADMIN_DIALOG          977
#define IDR_CONMENU_NOTSELECTED_INSERT  978
#define IDR_CONMENU_SELECTED_DELETE     979
#define IDR_CONMENU_SELECTED_DELETE_CHARACTER	980
#define IDR_CONMENU_SELECTED_INSERT     981
#define IDR_CONMENU_SELECTED_UPDATE     982
#define IDR_CONTEXT_MENU_DELETED_CHARACTER	983
#define IDR_CONTEXT_MENU_EVENT_MONSTER_MENAGEMENT	984
#define IDR_CONTEXT_MENU_GRID_BAD_USER  985
#define IDR_CONTEXT_MENU_GRID_ITEM      986
#define IDR_CONTEXT_MENU_GRID_SERVER    987
#define IDR_CONTEXT_MENU_HAPPYEV        988
#define IDR_CONTEXT_MENU_STRATEGYPOINT  989
#define IDR_MAINFRAME                   990
#define IDR_MENU_TRAY                   991
#define IDR_WAVE_ALERT                  992
#define IDS_LOG_PRO_SHEET               993
#define IDD_MARKET_TAB_RETURN           1000
#define IDD_DLG_WP_SHOP_MANAGEMENT      1001
#define IDB_BITMAP1                     1002
#define IDC_CHECK_AUCTION_INFLUENCE     1200
#define IDC_GRID_RETURN_AUCTION         1201
#define IDC_BUTTON_AUTCION_SEARCH       1202
#define IDC_BUTTON_AUTCION_RESET        1203
#define IDC_BUTTON_AUTCION_SAVE_RESULT  1204
#define IDC_CHECK_AUCTION_DATE          1205
#define IDC_DATETIMEPICKER_START_DATE_AUCTION 1206
#define IDC_CHECK_AUCTION_CHARACTER_NAME 1207
#define IDC_EDIT_AUCTION_CHARACTER_NAME 1208
#define IDC_CHECK_AUCTION_CHARACTER_UID 1209
#define IDC_EDIT_AUCTION_CHARACTER_UID  1210
#define IDC_CHECK_AUCTION_ITEM_UID      1211
#define IDC_CHECK_AUCTION_ITEM_NUM      1213
#define IDC_EDIT_AUCTION_ITEM_NUM       1214
#define IDC_CHECK_AUCTION_MAX_ROW_COUNT 1215
#define IDC_EDIT_AUCTION_ITEM_MAX_LOG_COUNT 1216
#define IDC_EDIT_AUCTION_ITEM_UID       1217
#define ID_UPDATE_TO_DB                 1218
#define IDC_GRID_WPSHOP_LIST            1219

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        1003
#define _APS_NEXT_COMMAND_VALUE         1100
#define _APS_NEXT_CONTROL_VALUE         1220
#define _APS_NEXT_SYMED_VALUE           1300
#endif
#endif
